### ISSUE TITLE
Only changes files that are currently open

### ISSUE THREAD

**Issue by TeaDrivenDev** [jakubbielawa/LineEndingsUnifier#8] opened 2017-03-16 03:33 UTC
When running "Unify line endings in this folder" on a folder in Solution Explorer, the completion message box will show what *should* have happened, but no files are actually changed.
When a file that needs to be changed is currently open in Visual Studio, the correct changes will be applied to the text buffer, but the file will not be saved (which can be seen as correct behavior).

Tested in both VS 2015 Update 3 and VS 2017 with the latest update applied.

**Comment by jakubbielawa** [comment] 2017-03-17 00:28
Hi, could you please write how you configured the extension in Options?

**Comment by TeaDrivenDev** [comment] 2017-03-17 15:50
I wasn't aware there were settings, so they're all the default values.

**Comment by jakubbielawa** [comment] 2017-04-03 21:49
@TeaDrivenDev Hi, I'm sorry for the delay. I managed to reproduce the issue with nothing actually happening when running "Unify line endings in this folder".
The second thing you mentioned is not a bug - the default value for "Save Files After Unifying" option is False.

**Comment by jakubbielawa** [comment] 2017-04-04 01:57
@TeaDrivenDev I've just uploaded a new version of the extension. The bug should be fixed now. Please let me know whether the issue here can be closed or not.

**Comment by jakubbielawa** [comment] 2017-06-15 15:20
Closing due to lack of activity.

**Closed by jakubbielawa** 2017-06-15 15:20 UTC
Labels: bug
